@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Change Password
actor User as act

participant "ChangePasswordView" as view
participant "LoginView" as r_view
participant "AccountController" as fe_ctrl <<frontend controller>>
participant ":ChangePasswordRequestDTO" as be_req
participant "ProfileController" as be_ctrl <<backend controller>>
participant ":IUserProfileService" as sv
participant ":IUserRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:1. Enter current, new, and confirm passwords
act->view:2. Click "Change Password"

view->view++:3. Validate input
view--

view->fe_ctrl++:4. POST /Account/ChangePassword

fe_ctrl->fe_ctrl++:5. Check AccessToken cookie
fe_ctrl--

fe_ctrl->be_req++:6. Call ChangePasswordRequestDTO()
be_req-->>fe_ctrl--:7. Return ChangePasswordRequestDTO object

fe_ctrl->be_ctrl++:8. POST /api/Profile/change-password

be_ctrl->be_ctrl++:9. Validate ModelState & login session
be_ctrl--

be_ctrl->sv++:10. Call ChangePasswordAsync(userId, req.CurrentPassword, req.NewPassword)

sv->repo++:11. Call GetUserByIdAsync(userId)
repo->ctx++:12. Query User joined with navigation details
ctx->db++:13. Execute query
db-->>ctx--:14. Return result
ctx-->>repo--:15. Return User entity
repo-->>sv--:16. Return User entity

sv->sv++:17. Verify User, Account, and Current Password
sv--

sv->sv++:18. Hash newPassword and update Account properties
sv--

sv->repo++:19. Call UpdateAccountAsync(account)
repo->ctx++:20. Mark Account as modified
ctx-->>repo--:21. Return result

repo->ctx++:22. Call SaveChangesAsync()
ctx->db++:23. Execute query
db-->>ctx--:24. Return result
ctx-->>repo--:25. Return numberOfRowsAffected

repo->repo++:26. Check numberOfRowsAffected
repo--

repo-->>sv--:27. Return true
sv-->>be_ctrl--:28. Return (true, success message)
be_ctrl-->>fe_ctrl--:29. Return statusCode 200

fe_ctrl->be_ctrl++:30. POST /api/Auth/logout
be_ctrl-->>fe_ctrl--:31. Return statusCode 200

fe_ctrl->fe_ctrl++:32. Delete authentication cookies
fe_ctrl--

fe_ctrl-->>view--:33. Return statusCode 302
view-->>act--:34. Redirect to Login page
act->r_view++:35. Access Login page
r_view-->>act--:36. Display login page with success message
@enduml
