@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Logout
actor User as act

participant "Navbar / Layout" as view
participant "AccountController (FE)" as fe_ctrl
participant "AuthController (BE)" as be_ctrl
participant ":AuthService" as auth_sv
database Database as db

act++
act->view++: Click "Logout" button
view->fe_ctrl++: Send POST request to /Account/Logout (with Anti-forgery Token)

fe_ctrl->be_ctrl++: Send POST /api/auth/logout (with Bearer Token)

be_ctrl->be_ctrl++: Extract accountId from User claims
be_ctrl--

be_ctrl->auth_sv++: Call LogoutAsync(accountId)
auth_sv->db++: Delete / revoke active RefreshToken from DB
db-->>auth_sv--: Return success
auth_sv->db++: Commit changes
db-->>auth_sv--: Return success
auth_sv-->>be_ctrl--: Return completion Task

be_ctrl->be_ctrl++: Clear API cookies (AccessToken, RefreshToken)
be_ctrl--
be_ctrl-->>fe_ctrl--: Return statusCode 200 (Ok)

fe_ctrl->fe_ctrl++: Delete FE cookies (AccessToken, RefreshToken, UserName,\nAvatarUrl, UserRole, UserId, InstructorApprovalStatus)
fe_ctrl--

fe_ctrl-->>view--: Redirect to GET /Home/Index
view-->>act--: Display homepage in logged-out state (with Login/Register buttons)
@enduml
