@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Logout
actor "User/Instructor/Staff/Admin" as act

participant "NavbarView" as view
participant "HomeIndexView" as home_view
participant "AccountController" as fe_ctrl <<frontend controller>>
participant "AuthController" as be_ctrl <<backend controller>>
participant ":IAuthService" as sv
participant ":IUserRepository" as u_repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++: Click "Logout" button
view->fe_ctrl++: POST /Account/Logout
deactivate view

fe_ctrl->be_ctrl++: POST /api/auth/logout

be_ctrl->be_ctrl++: Extract accountId from User claims
be_ctrl--

opt accountId is valid
    be_ctrl->sv++: Call LogoutAsync(accountId)
    sv->u_repo++: Call RevokeRefreshTokenAsync(accountId)
    u_repo->ctx++: Set RefreshToken = null
    ctx-->>u_repo--: Return result
    
    u_repo->ctx++: Call SaveChangesAsync()
    ctx->db++: Save changes to database
    db-->>ctx--: Return numberOfRowsAffected
    ctx-->>u_repo--: Return numberOfRowsAffected
    
    u_repo-->>sv--: Return numberOfRowsAffected
    sv-->>be_ctrl--: Return result
end

be_ctrl->be_ctrl++: Clear API cookies (AccessToken, RefreshToken)
be_ctrl--

be_ctrl-->>fe_ctrl--: Return statusCode 200

fe_ctrl->fe_ctrl++: Delete FE cookies (AccessToken, RefreshToken, UserName, AvatarUrl, UserRole, UserId)
fe_ctrl--

fe_ctrl -->> home_view--: Redirect to Home Index page
activate home_view
home_view -->> act--: Display homepage in logged-out state
@enduml
