@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Register
actor Guest as act

participant "RegisterFormView" as view
participant "VerifyRecommendView" as r_view
participant "AccountController" as fe_ctrl <<frontend controller>>
participant "AuthController" as be_ctrl <<backend controller>>
participant ":RegisterRequestDTO" as req
participant ":IAuthService" as sv
participant ":Account" as acc_ett
participant ":User" as user_ett
participant ":IUserRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++: Enter details and click "Register"
view->fe_ctrl++: POST /Account/Register

fe_ctrl->fe_ctrl++: Validate ModelState and email domain
fe_ctrl--

alt Invalid ModelState or email domain
    fe_ctrl-->>view: Return statusCode 400
    view-->>act: Display error message
else Valid ModelState and email domain
    fe_ctrl->be_ctrl++: POST /api/auth/register

    be_ctrl->req++: Call RegisterRequestDTO()
    req-->>be_ctrl--: Return RegisterRequestDTO object

    be_ctrl->sv++: Call RegisterAsync(req)

    sv->sv++: Validate registration request
    sv--

    alt Invalid registration request
        sv-->>be_ctrl: Return validation error message
        be_ctrl-->>fe_ctrl: Return statusCode 400
        fe_ctrl-->>view: Return statusCode 400
        view-->>act: Display error message
    else Valid registration request
        sv->sv++: Hash password using BCrypt
        sv--

        sv->acc_ett++: Call Account()
        acc_ett-->>sv--: Return Account entity
        
        sv->user_ett++: Call User()
        user_ett-->>sv--: Return User entity

        sv->repo++: Call RegisterUserAsync(acc, user)
        repo->ctx++: Add Account & User to DbSets and call SaveChangesAsync()
        ctx->db++: Save changes to database
        db-->>ctx--: Return numberOfRowsAffected
        ctx-->>repo--: Return numberOfRowsAffected

        repo->repo++: Check numberOfRowsAffected
        repo--

        alt numberOfRowsAffected = 0
            repo-->>sv: Return false
            sv-->>be_ctrl: Return "Error"
            be_ctrl-->>fe_ctrl: Return statusCode 400
            fe_ctrl-->>view: Return statusCode 400
            view-->>act: Display error message
            deactivate view
        else numberOfRowsAffected > 0
            repo-->>sv--: Return true
            sv-->>be_ctrl--: Return "Success"
            be_ctrl-->>fe_ctrl--: Return statusCode 200
            
            deactivate view
            fe_ctrl-->>r_view--: Redirect to VerifyRecommend page
            activate r_view
            r_view-->>act--: Display VerifyRecommend page
        end
    end
end
@enduml
