@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe Search Courses

actor Admin as act
participant "CourseModerationPage" as view
participant "AdminModerationController" as fe_ctrl <<frontend controller>>
participant "AdminModerationController" as be_ctrl <<backend controller>>
participant ":CourseModerationService" as sv
participant ":ICourseRepository" as repo
participant ":PagedResult<CourseModerationDto>" as res
participant ":AppDbContext" as ctx
database Database as db

act ++
act -> view++: Enter keyword and click Search
view -> fe_ctrl++: GET /AdminModeration/Pending?keyword={keyword}
fe_ctrl -> be_ctrl++: GET /api/admin-moderation/courses/pending?keyword={keyword}

be_ctrl -> sv++: Call GetPendingCoursesAsync(filter)

sv -> repo++: Call GetPendingCoursesModerationAsync(filter)
repo -> ctx++: Execute query
ctx -> db++: Fetch pending courses
db -->> ctx--: Return query results
ctx -->> repo--: Return entities and totalCount

repo -> res++: Call PagedResult(courses, totalCount)
res -->> repo--: Return PagedResult object

repo -->> sv--: Return PagedResult object
sv -->> be_ctrl--: Return PagedResult object

be_ctrl -->> fe_ctrl--: Return statusCode 200
fe_ctrl -->> view--: Return View(PagedResult)
view -->> act--: Display list of pending courses