@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe Delete Message

actor User as act
participant "ChatRoom" as view
participant "ErrorPage" as error_page
participant "ChatController" as fe_ctrl <<frontend controller>>
participant "ChatController" as be_ctrl <<backend controller>>
participant ":IChatService" as sv
participant ":IChatRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act ++
act -> view++: Click "Delete for me"
view -> view++: deleteMsg(messageId)
view--
view -> fe_ctrl++: DELETE /Chat/DeleteMessage?messageId={id}
fe_ctrl -> be_ctrl++: DELETE /api/chat/message/{id}
be_ctrl -> sv++: Call DeleteMessageAsync(messageId, accountId)

sv -> repo++: Call GetMessageByIdAsync(messageId)
repo -> ctx++: FindAsync(messageId)
ctx -> db++: Execute query
db -->> ctx--: Return data
ctx -->> repo--: Return Entity object
repo -->> sv--: Return Message object

alt Message found and is Sender
    sv -> sv++: Update message.MessageStatus = "deleted_by_sender"
    sv--
    sv -> repo++: Call SaveChangesAsync()
    repo -> ctx++: SaveChangesAsync()
    ctx -> db++: Save changes to database
    db -->> ctx--: Return numberOfRowsAffected
    ctx -->> repo--: Return numberOfRowsAffected
    repo -->> sv--: Return numberOfRowsAffected
    
    sv -> sv++: Check numberOfRowsAffected
    sv--
    
    alt numberOfRowsAffected > 0
        sv -->> be_ctrl: Return chatId
        
        be_ctrl -> be_ctrl++: Broadcast "MessageDeleted" to User_{accountId} via SignalR
        be_ctrl--
        
        be_ctrl -->> fe_ctrl: Return statusCode 200
        fe_ctrl -->> view: Return statusCode 200
        view -> view++: Remove message element from DOM
        view--
        view -->> act: Message is hidden from view
    else numberOfRowsAffected = 0
        sv -->> be_ctrl--: throw InvalidOperationException
        be_ctrl -->> fe_ctrl--: Return statusCode 500
        fe_ctrl -->> view--: Return statusCode 500
        view -->> act--: Display error message
    end
else Message not found
    sv -->> be_ctrl: throw KeyNotFoundException
    be_ctrl -->> fe_ctrl: Return statusCode 404
    fe_ctrl -->> view: Return statusCode 404
    view -->> act: Display error message
else Unauthorized (Not sender)
    sv -->> be_ctrl: throw UnauthorizedAccessException
    be_ctrl -->> fe_ctrl: Return statusCode 403
    fe_ctrl-->>error_page++: Redirect to ErrorPage
    error_page-->>act--: Display error message
end
@enduml
