@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe View Notification List
actor Admin as act

participant "Admin.cshtml" as view
participant "NotificationController" as fe_ctrl
participant "NotificationController" as be_ctrl
participant ":NotificationService" as sv
participant ":NotificationHub" as hub
participant ":NotificationRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:Access System Notifications page
view->fe_ctrl++:Send GET request to Notification/Admin
fe_ctrl-->>view:Return Admin View (HTML)


act->view++:Page finishes loading in browser
view->view:Validate Access Token
view--
group opt [Token is missing or expired]
    view-->>act:Redirect to Login Page
end

view->hub++:Start SignalR connection to /notificationHub (with AccessToken)
hub-->>view:Connection established successfully

view->be_ctrl++:Send GET request to /api/Notification/all (with Bearer Token)

be_ctrl->be_ctrl++:Authorize Admin or Staff role
be_ctrl--
group opt [Unauthorized]
    be_ctrl-->>view:Return statusCode 401 (Unauthorized)
    view-->>act:Display Access Denied message
end

be_ctrl->sv++:Call GetAllNotificationsForAdminAsync()
sv->repo++:Call AutoCleanupAdminNotificationsAsync()
repo->ctx++:Query old read notifications (> 90 days)
ctx->db++:Execute SELECT query
db-->>ctx--:Return old notifications list
ctx-->>repo--:Return old notifications list

repo->repo++:Check if old notifications exist
repo--
group opt [Old notifications found]
    repo->ctx++:Mark IsRemoved = true for old notifications
    ctx-->>repo--:Return
    repo->ctx++:Call SaveChangesAsync()
    ctx->db++:Update IsRemoved = true in Database
    db-->>ctx--:Return numberOfRowsAffected
    ctx-->>repo--:Return result
end
repo-->>sv--:Return

sv->repo++:Call GetAllAsync()
repo->ctx++:Call GetAllAsync() (with Include Receiver and User)
ctx->db++:Query active notifications
db-->>ctx--:Return active notifications list
ctx-->>repo--:Return active notifications list
repo-->>sv--:Return active notifications list

sv->sv++:Map to NotificationAdminResponseDto list
sv--
sv-->>be_ctrl--:Return NotificationAdminResponseDto list
be_ctrl-->>view--:Return statusCode 200 (Ok) with JSON list

view->view++:Validate and apply default filters/sorting
view--

view->view++:Render active notifications in admin-table-body
view--

view-->>act--:Display system notifications list
@enduml
