START TRANSACTION;

ALTER TABLE courses RENAME COLUMN "ThreatLevel" TO threat_level;

ALTER TABLE managers ADD avatar_url text;

ALTER TABLE managers ADD bio text;

ALTER TABLE managers ADD full_name character varying(255);

ALTER TABLE managers ADD phone_number character varying(50);

ALTER TABLE instructors ADD rejection_reason text;

ALTER TABLE courses ALTER COLUMN threat_level SET DEFAULT 1;

CREATE TABLE gifts (
    gift_id integer GENERATED BY DEFAULT AS IDENTITY,
    order_item_id integer NOT NULL,
    sender_id integer,
    recipient_email character varying(255) NOT NULL,
    recipient_name character varying(255),
    gift_message text,
    card_theme character varying(50) DEFAULT 'classic',
    redemption_token character varying(255) NOT NULL,
    is_claimed boolean NOT NULL DEFAULT FALSE,
    claimed_by_user_id integer,
    claimed_at timestamp without time zone,
    delivery_status character varying(50) DEFAULT 'pending',
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT gifts_pkey PRIMARY KEY (gift_id),
    CONSTRAINT gifts_claimed_by_user_id_fkey FOREIGN KEY (claimed_by_user_id) REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT gifts_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items (id) ON DELETE CASCADE,
    CONSTRAINT gifts_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES accounts (account_id) ON DELETE SET NULL
);

CREATE TABLE quiz_questions (
    question_id integer GENERATED BY DEFAULT AS IDENTITY,
    course_id integer NOT NULL,
    lesson_id integer NOT NULL,
    question_text text NOT NULL,
    question_type character varying(20) NOT NULL DEFAULT 'SingleChoice',
    order_index integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT quiz_questions_pkey PRIMARY KEY (question_id),
    CONSTRAINT quiz_questions_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE,
    CONSTRAINT quiz_questions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (lesson_id) ON DELETE CASCADE
);

CREATE TABLE quizzes (
    quiz_id integer GENERATED BY DEFAULT AS IDENTITY,
    instructor_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    time_limit_minutes integer,
    passing_score integer NOT NULL DEFAULT 70,
    total_questions integer NOT NULL DEFAULT 10,
    course_id integer NOT NULL,
    is_hidden boolean NOT NULL DEFAULT FALSE,
    is_removed boolean NOT NULL DEFAULT FALSE,
    created_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT quizzes_pkey PRIMARY KEY (quiz_id),
    CONSTRAINT quizzes_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE,
    CONSTRAINT quizzes_instructor_id_fkey FOREIGN KEY (instructor_id) REFERENCES instructors (instructor_id) ON DELETE CASCADE
);

CREATE TABLE quiz_options (
    option_id integer GENERATED BY DEFAULT AS IDENTITY,
    question_id integer NOT NULL,
    option_text text NOT NULL,
    is_correct boolean NOT NULL DEFAULT FALSE,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT quiz_options_pkey PRIMARY KEY (option_id),
    CONSTRAINT quiz_options_question_id_fkey FOREIGN KEY (question_id) REFERENCES quiz_questions (question_id) ON DELETE CASCADE
);

CREATE TABLE course_quizzes (
    course_quiz_id integer GENERATED BY DEFAULT AS IDENTITY,
    course_id integer NOT NULL,
    quiz_id integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    is_hidden boolean NOT NULL DEFAULT FALSE,
    added_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT course_quizzes_pkey PRIMARY KEY (course_quiz_id),
    CONSTRAINT course_quizzes_course_id_fkey FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE,
    CONSTRAINT course_quizzes_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES quizzes (quiz_id) ON DELETE CASCADE
);

CREATE TABLE quiz_attempts (
    attempt_id integer GENERATED BY DEFAULT AS IDENTITY,
    quiz_id integer NOT NULL,
    user_id integer NOT NULL,
    score integer,
    is_passed boolean,
    started_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    submitted_at timestamp without time zone,
    CONSTRAINT quiz_attempts_pkey PRIMARY KEY (attempt_id),
    CONSTRAINT quiz_attempts_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES quizzes (quiz_id) ON DELETE CASCADE,
    CONSTRAINT quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE quiz_lesson_distributions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    quiz_id integer NOT NULL,
    lesson_id integer NOT NULL,
    percentage integer NOT NULL DEFAULT 0,
    CONSTRAINT quiz_lesson_distributions_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_lesson_distributions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (lesson_id) ON DELETE CASCADE,
    CONSTRAINT quiz_lesson_distributions_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES quizzes (quiz_id) ON DELETE CASCADE
);

CREATE TABLE quiz_attempt_answers (
    answer_id integer GENERATED BY DEFAULT AS IDENTITY,
    attempt_id integer NOT NULL,
    question_id integer NOT NULL,
    selected_option_id integer,
    CONSTRAINT quiz_attempt_answers_pkey PRIMARY KEY (answer_id),
    CONSTRAINT quiz_attempt_answers_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (attempt_id) ON DELETE CASCADE,
    CONSTRAINT quiz_attempt_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES quiz_questions (question_id) ON DELETE CASCADE,
    CONSTRAINT quiz_attempt_answers_selected_option_id_fkey FOREIGN KEY (selected_option_id) REFERENCES quiz_options (option_id) ON DELETE SET NULL
);

CREATE TABLE quiz_attempt_questions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    attempt_id integer NOT NULL,
    question_id integer NOT NULL,
    order_index integer NOT NULL DEFAULT 0,
    CONSTRAINT quiz_attempt_questions_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_attempt_questions_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES quiz_attempts (attempt_id) ON DELETE CASCADE,
    CONSTRAINT quiz_attempt_questions_question_id_fkey FOREIGN KEY (question_id) REFERENCES quiz_questions (question_id) ON DELETE CASCADE
);

CREATE INDEX "IX_course_quizzes_quiz_id" ON course_quizzes (quiz_id);

CREATE UNIQUE INDEX uq_course_quiz ON course_quizzes (course_id, quiz_id);

CREATE INDEX idx_gifts_delivery ON gifts (delivery_status);

CREATE INDEX idx_gifts_recipient ON gifts (recipient_email);

CREATE UNIQUE INDEX idx_gifts_token ON gifts (redemption_token);

CREATE INDEX "IX_gifts_claimed_by_user_id" ON gifts (claimed_by_user_id);

CREATE INDEX "IX_gifts_order_item_id" ON gifts (order_item_id);

CREATE INDEX "IX_gifts_sender_id" ON gifts (sender_id);

CREATE INDEX "IX_quiz_attempt_answers_attempt_id" ON quiz_attempt_answers (attempt_id);

CREATE INDEX "IX_quiz_attempt_answers_question_id" ON quiz_attempt_answers (question_id);

CREATE INDEX "IX_quiz_attempt_answers_selected_option_id" ON quiz_attempt_answers (selected_option_id);

CREATE INDEX "IX_quiz_attempt_questions_question_id" ON quiz_attempt_questions (question_id);

CREATE UNIQUE INDEX uq_quiz_attempt_question ON quiz_attempt_questions (attempt_id, question_id);

CREATE INDEX "IX_quiz_attempts_quiz_id" ON quiz_attempts (quiz_id);

CREATE INDEX "IX_quiz_attempts_user_id" ON quiz_attempts (user_id);

CREATE INDEX "IX_quiz_lesson_distributions_lesson_id" ON quiz_lesson_distributions (lesson_id);

CREATE UNIQUE INDEX uq_quiz_lesson_dist ON quiz_lesson_distributions (quiz_id, lesson_id);

CREATE INDEX "IX_quiz_options_question_id" ON quiz_options (question_id);

CREATE INDEX "IX_quiz_questions_course_id" ON quiz_questions (course_id);

CREATE INDEX "IX_quiz_questions_lesson_id" ON quiz_questions (lesson_id);

CREATE INDEX "IX_quizzes_course_id" ON quizzes (course_id);

CREATE INDEX "IX_quizzes_instructor_id" ON quizzes (instructor_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260620092312_UpdateQuizArchitecture', '8.0.25');

COMMIT;

