@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Create Course
actor Instructor as act

participant "CourseCreationForm" as view


participant "InstructorCourseController" as fe_ctrl
participant "CourseController" as be_ctrl



participant ":CourseCommandService" as sv
participant ":CourseResponse" as res
participant ":Course" as ett

participant ":CourseRepository" as repo
participant ":AppDbContext" as ctx

Database Database as db

act++
act->view++:Access course creation form
act->view:Enter required data
act->view:Click the "Create Course" button
view->view++:Validate input
view--
group opt [Invalid input]
    view-->>act:Display error message
end

view->fe_ctrl++:Send POST request to InstructorCourse/Create
fe_ctrl->fe_ctrl++: Validate ModelState
fe_ctrl--
group opt [Invalid ModelState]
    fe_ctrl-->>view: Return status code 400 
    view-->>act:Display error message
end
fe_ctrl->be_ctrl++: Send POST request to /courses
be_ctrl -> sv++: Call CreateCourseAsync()
sv -> sv++: Call CheckInstructorRights()
sv--



sv -> ett++: Call Course()
ett -->>sv--: Return Course object
sv -> repo++: Call AddAsync()
repo->ctx++: Call AddAsync()
ctx-->>repo--: Return result
repo -->> sv--: Return result
sv -> repo++: Call SaveChangesAsync()
repo->ctx++: Call SaveChangesAsync()
ctx->db++: Save changes to Database
db-->>ctx--: Return numberOfRowsAffected
ctx-->>repo--: Return numberOfRowsAffected
repo -->> sv--: Return numberOfRowsAffected
sv->sv++:Check numberOfRowsAffected
sv--
alt numberOfRowsAffected > 0
    sv -> sv++: Call UpdateCourseHashesAsync()
    sv--
    sv -> res++: Call CourseResponse()
    res -->> sv--: Return CourseResponse object
    sv -->>  be_ctrl: Return CourseResponse object
    be_ctrl -->> fe_ctrl:Return statusCode 201
    fe_ctrl -->> view: Return statusCode 201
    view -->> act: Display course creation success message
else numberOfRowsAffected = 0
    sv-->>be_ctrl--:throw InvalidOperationException
    be_ctrl -->> fe_ctrl--:Return statusCode 400
    fe_ctrl -->> view--: Return statusCode 400
    view -->> act --: Display error message
end

@enduml