@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe View Quiz List

actor Instructor as act
participant "QuizListPage" as view
participant "QuizController" as fe_ctrl <<frontend controller>>
participant "QuizController" as be_ctrl <<backend controller>>
participant ":QuizService" as sv
participant ":QuizListResponse" as res
participant ":IQuizRepository" as repo

act ++
act -> view++: Access quiz list page
view -> fe_ctrl++: GET /Quiz/Index

fe_ctrl -> be_ctrl++: GET /api/quizzes

be_ctrl -> sv++: Call GetInstructorQuizzesAsync(instructorId)

sv -> repo++: Call GetQuizzesByInstructorAsync(instructorId)
repo -->> sv--: Return List<Quiz>

loop For each Quiz in list
    sv -> res++: Call QuizListResponse()
    res -->> sv--: Return QuizListResponse object
end

sv -->> be_ctrl--: Return List<QuizListResponse>
be_ctrl -->> fe_ctrl--: Return statusCode 200

fe_ctrl -> fe_ctrl++: Parse JSON to List<QuizSummaryItem>
fe_ctrl--

fe_ctrl -->> view--: Return View with QuizListViewModel
view -->> act--: Display quizzes
