@startuml HideCourse

hide empty members

class InstructorCourseController {
    + Hide()
}

class CourseController {
    + HideCourse()
}

interface ICourseService {
    + HideCourseAsync()
}

class CourseService {
    + HideCourseAsync()
}

interface ICourseRepository {
    + GetByIdAsync()
    + Update()
    + SaveChangesAsync()
}

class CourseRepository {
    + GetByIdAsync()
    + Update()
    + SaveChangesAsync()
}

class Course {
    + CourseId
    + InstructorId
    + CourseStatus
    + IsHidden
}

class Instructor {
    + InstructorId
}

class ApplicationDbContext


' === RELATIONSHIPS ===
InstructorCourseController ..> CourseController
CourseController --> ICourseService
CourseService --> ICourseRepository
CourseRepository --> ApplicationDbContext
CourseService ..> Course
CourseRepository ..> Course
Instructor *-- Course
CourseService ..|> ICourseService
CourseRepository ..|> ICourseRepository

@enduml
