@startuml 
<style>
    sequenceDiagram{
        FontSize 16

        arrow {
            ' Set the maximum width of the text on arrows
            MaximumWidth 300

        }
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe View Transaction List

actor User as act
participant "PurchaseHistoryPage" as view
participant "LoginPage" as login_view
participant "ErrorPage" as error_view
participant "TransactionController" as fe_ctrl <<frontend controller>>
participant ":TransactionPagedVM" as vm
participant "TransactionController" as be_ctrl <<backend controller>>
participant ":ITransactionService" as sv
participant ":ITransactionRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act ++
act -> view++:1. Access purchase history page
view -> fe_ctrl++:2. GET /Transaction/History

fe_ctrl -> fe_ctrl++:3. Validate actor's authentication and authorization
fe_ctrl--

alt Session Invalid
    fe_ctrl -->> login_view:3.1. Redirect to LoginPage
    activate login_view
    login_view -->> act--:3.1.1. Display login form
else Unauthorized Access
    fe_ctrl -->> error_view:3.2. Redirect to ErrorPage
    activate error_view
    error_view -->> act--:3.2.1. Display error message
else Valid actor's authentication and authorization
    fe_ctrl -> vm++:3.3. Call TransactionPagedVM(page, pageSize)
    vm -->> fe_ctrl--:3.3.1. Return TransactionPagedVM object

fe_ctrl -> be_ctrl++:3.3.2. GET /api/transactions/my
be_ctrl -> sv++:3.3.3. GetUserTransactionsAsync(userId, page, pageSize, keyword, sortBy, status)

sv -> repo++:3.3.4. GetUserTransactionsAsync(userId, page, pageSize, keyword, sortBy, status)

repo -> ctx++:3.3.5. Calculate totalCount and query items
ctx -> db++:3.3.6. Execute query
db -->> ctx--:3.3.7. Return data
ctx -->> repo--:3.3.8. Return items and totalCount

repo -->> sv--:3.3.9. Return items and totalCount

    sv -->> be_ctrl--:3.3.10. Return PagedResult<TransactionListDto> object
    be_ctrl -->> fe_ctrl--:3.3.11. Return statusCode 200
    
    fe_ctrl -> fe_ctrl++:3.3.12. Deserialize JSON to TransactionPagedVM
    fe_ctrl--
    
    fe_ctrl -->> view--:3.3.13. Return View(vm)

    view -> view++:3.3.14. Check totalCount
    view--
alt Transaction history is empty (totalCount == 0)
        view -->> act:3.3.14.1. Display empty history card with "No transactions found" message
else Has transactions
        view -->> act--:3.3.14.2. Display list of transactions and total purchases metric
end
end

@enduml
