@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white   
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe View List of Refund Requests

actor "Administrator" as act
participant "AdminFinanceDashboard" as view
participant "LoginPage" as login_view
participant "AdminFinanceController" as fe_ctrl <<frontend controller>>
participant "AdminFinanceController" as be_ctrl <<backend controller>>
participant ":AdminFinanceService" as finance_sv
participant ":AdminFinanceRepository" as finance_repo
database Database as db

act ++
view ++

act -> view:1. Access Admin Finance Dashboard
view -> fe_ctrl++:2. GET /AdminFinance

fe_ctrl -> fe_ctrl:3. Validate active login session
alt Session Invalid (EX-1)
    fe_ctrl -->> login_view:3.1. Redirect to /Account/Login
    activate login_view
    login_view -->> act:3.1.1. Display authentication error message\nRedirect to login page
    deactivate login_view
else Valid Session
    fe_ctrl -> be_ctrl++:3.2. GET /api/admin/finance/refunds/pending
    be_ctrl -> finance_sv++:3.2.1. GetPendingRefundRequestsAsync()
    finance_sv -> finance_repo++:3.2.2. Query Pending Refund Requests from DB
    finance_repo -> db++:3.2.3. Execute SELECT
    db -->> finance_repo--:3.2.4. List of Transactions
    finance_repo -->> finance_sv--:3.2.5. List of Transactions
    finance_sv -->> be_ctrl--:3.2.6. PagedResult<Transaction>
    be_ctrl -->> fe_ctrl--:3.2.7. Return statusCode 200 (Data)
    
    fe_ctrl -> fe_ctrl:3.2.8. Map to AdminFinanceUnifiedVM
    fe_ctrl -->> view--:3.2.9. Return View(AdminFinanceUnifiedVM)
    
    act -> view:3.2.10. Click the "Refund Requests" tab
    
    view -->> act:3.2.11. Display refund requests table (Transaction ID, Course Title,\nStudent Name, Amount, Purchase Date, Request Date, Refund Reason)
end

@enduml
