@startuml 
<style>
    sequenceDiagram{
        FontSize 16

        arrow {
            ' Set the maximum width of the text on arrows
            MaximumWidth 300

        }
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe Report Course Review

actor User as act
participant "CourseDetailsPage" as view
participant "LoginPage" as login_view
participant "ErrorPage" as error_view
participant "ReportController" as fe_ctrl <<frontend controller>>
participant "ReportController" as be_ctrl <<backend controller>>
participant ":IReportSubmissionService" as sv
participant ":CourseReviewReport" as ett
participant ":IReportRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act ++
act -> view++: Click "Report" button on a course review
view -->> act: Display report review form modal
view--

act -> view++: Select reason, input description, click "Submit Report"

opt Invalid form input
    view -->> act: Display validation error message
end

view -> fe_ctrl++: POST /Report/ReportCourseReview

fe_ctrl -> fe_ctrl++: Validate actor's authentication and authorization
fe_ctrl--

alt Session Invalid
    fe_ctrl -->> login_view: Redirect to LoginPage
    activate login_view
    login_view -->> act--: Display login form
else Unauthorized Access
    fe_ctrl -->> error_view: Redirect to ErrorPage
    activate error_view
    error_view -->> act--: Display error message
else Valid actor's authentication and authorization
    fe_ctrl -> fe_ctrl++: Validate ModelState
    fe_ctrl--
    
    opt Invalid ModelState
        fe_ctrl -->> view: Return BadRequest()
        view -->> act: Display error message
    end

    fe_ctrl -> be_ctrl++: POST /api/report/course-reviews
    be_ctrl -> sv++: Call CreateCourseReviewReportAsync(reporterId, request)
    
    sv -> sv++: Validate course review report request
    sv--
    
    alt Review Not Found
        sv -->> be_ctrl: throw KeyNotFoundException
        be_ctrl -->> fe_ctrl: Return statusCode 404
        fe_ctrl -->> view: Return NotFound()
        view -->> act: Display error message
    else Validation Failure
        sv -->> be_ctrl: throw BadRequestException
        be_ctrl -->> fe_ctrl: Return statusCode 400
        fe_ctrl -->> view: Return BadRequest()
        view -->> act: Display error message
    else Valid course review report request
        sv -> ett++: Call CourseReviewReport()
        ett -->> sv--: Return CourseReviewReport object

        sv -> repo++: AddCourseReviewReportAsync(report)
        repo -> ctx++: Add(report)
        ctx -->> repo: Return result
        ctx--
        repo -->> sv: Return result
        repo--
        
        sv -> sv++: Call SaveChangesAndHandleExceptionsAsync()
        sv -> repo++: SaveChangesAsync()
        repo -> ctx++: SaveChangesAsync()
        ctx -> db++: Save changes to database
        
        alt Database Save Failure
            db -->> ctx: throw DbUpdateException
            ctx -->> repo: throw DbUpdateException
            repo -->> sv: throw ReportException
            sv -->> be_ctrl: throw BadRequestException
            be_ctrl -->> fe_ctrl: Return statusCode 400
            fe_ctrl -->> view: Return BadRequest()
            view -->> act: Display error message regarding report submission failure
        else Database Save Success
            db -->> ctx: Return result
            db--
            ctx -->> repo: Return result
            ctx--
            repo -->> sv: Return result
            repo--
            sv--
            
            sv -> sv++: Call NotifyManagersAsync()
            sv--
            
            sv -->> be_ctrl: Return true
            sv--
            be_ctrl -->> fe_ctrl--: Return statusCode 200
            fe_ctrl -->> view--: Return Ok()
            view -->> act--: Display success message regarding report submission
        end
    end
end
@enduml
