@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Delete Coupon

actor Admin as act
participant "CouponListView" as view
participant "CouponController" as be_ctrl <<backend controller>>
participant ":ICouponService" as sv
participant ":ICouponRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:1. Click "Delete" on a Coupon
view->be_ctrl++:2. DELETE /api/coupon/{id}

be_ctrl->sv++:3. SoftDelete(id, GetUserId(), isAdmin)

sv->repo++:4. GetByIdAsync(id, filterId)
repo->ctx++:5. Query coupon
ctx->db++:6. Execute query
db-->>ctx--:7. Return result
ctx-->>repo--:8. Return Coupon entity
repo-->>sv--:9. Return Coupon entity

sv->sv++:10. Validate coupon deletion request
sv--

alt Coupon not found
    sv-->>be_ctrl:10.1. throw KeyNotFoundException
    be_ctrl-->>view:10.1.1. Return statusCode 404
    view-->>act:10.1.2. Display error message
else Valid coupon deletion request
    sv->sv++:10.2. Set IsActive = false and EndDate = yesterday
    sv--
    
    sv->repo++:10.2.1. Update(coupon)
    repo->ctx++:10.2.2. Mark entity as modified
    ctx-->>repo--:10.2.3. Return result
    repo-->>sv--:10.2.4. Return result
    
    sv->repo++:10.2.5. SaveChangesAsync()
    repo->ctx++:10.2.6. Commit tracked changes
    ctx->db++:10.2.7. Save changes to database
    db-->>ctx--:10.2.8. Return result
    ctx-->>repo--:10.2.9. Return numberOfRowsAffected
    repo-->>sv--:10.2.10. Return success
    
    sv-->>be_ctrl--:10.2.11. Return result
    be_ctrl-->>view--:10.2.12. Return statusCode 200
    view-->>act--:10.2.13. Display success message
end
@enduml
