@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Edit Coupon

actor Admin as act
participant "CouponListView" as view
participant "CouponController" as be_ctrl <<backend controller>>
participant ":UpdateCouponRequestDTO" as be_req
participant ":ICouponService" as sv
participant ":ICouponRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:1. Click "Edit" and submit form
view->be_ctrl++:2. PUT /api/coupon/{id}

be_ctrl->be_req++:3. Call UpdateCouponRequestDTO()
be_req-->>be_ctrl--:4. Return UpdateCouponRequestDTO object

be_ctrl->sv++:5. Update(id, req, GetUserId(), isAdmin)

sv->repo++:6. GetByIdAsync(id, filterId)
repo->ctx++:7. Query coupon
ctx->db++:8. Execute query
db-->>ctx--:9. Return result
ctx-->>repo--:10. Return Coupon entity
repo-->>sv--:11. Return Coupon entity

sv->sv++:12. Validate coupon update request
sv--

alt Coupon not found
    sv-->>be_ctrl:12.1. throw KeyNotFoundException
    be_ctrl-->>view:12.1.1. Return statusCode 404
    view-->>act:12.1.2. Display error message
else Invalid EndDate or UsageLimit
    sv-->>be_ctrl:12.2. throw ArgumentException
    be_ctrl-->>view:12.2.1. Return statusCode 400
    view-->>act:12.2.2. Display error message
else Valid coupon update request
    sv->sv++:12.3. Update EndDate, UsageLimit, IsActive
    sv--
    
    sv->repo++:12.3.1. Update(coupon)
    repo->ctx++:12.3.2. Mark entity as modified
    ctx-->>repo--:12.3.3. Return result
    repo-->>sv--:12.3.4. Return result
    
    sv->repo++:12.3.5. SaveChangesAsync()
    repo->ctx++:12.3.6. Commit tracked changes
    ctx->db++:12.3.7. Save changes to database
    db-->>ctx--:12.3.8. Return result
    ctx-->>repo--:12.3.9. Return numberOfRowsAffected
    repo-->>sv--:12.3.10. Return success
    
    sv-->>be_ctrl--:12.3.11. Return result
    be_ctrl-->>view--:12.3.12. Return statusCode 200
    view-->>act--:12.3.13. Display success message
end
@enduml
