@startuml
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe Sort Coupons

actor Admin as act
participant "CouponListView" as view
participant "CouponController" as be_ctrl <<backend controller>>
participant ":CouponResponseDTO" as res_dto
participant ":ICouponService" as sv
participant ":ICouponRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:1. Access coupon list page
view->be_ctrl++:2. GET /api/coupon

be_ctrl->sv++:3. GetAll(GetUserId(), isActive, type, search, isAdmin)

sv->repo++:4. GetAllAsync(filterId, isActive, type, search)
repo->ctx++:5. Query coupons
ctx->db++:6. Execute query
db-->>ctx--:7. Return result
ctx-->>repo--:8. Return list of Coupons
repo-->>sv--:9. Return list of Coupons

sv->res_dto++:10. Call CouponResponseDTO()
res_dto-->>sv--:11. Return CouponResponseDTO object

sv-->>be_ctrl--:12. Return list of CouponResponseDTO objects
be_ctrl-->>view--:13. Return statusCode 200
view-->>act--:14. Display coupons list

act->view++:15. Click on table header column to sort
view->view++:16. Sort cached coupon list in memory
view--
view-->>act--:17. Display sorted coupons list
@enduml
