@startuml 
<style>
    sequenceDiagram{
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox

mainframe View Coupon List
actor Admin as act

participant "AdminCouponView" as view
participant "CouponController" as be_ctrl <<backend controller>>
participant ":CouponResponseDTO" as res_dto
participant ":ICouponService" as sv
participant ":ICouponRepository" as repo
participant ":AppDbContext" as ctx
database Database as db

act++
act->view++:1. Access "Voucher Center" page / Search & Filter Coupons
view->be_ctrl++:2. GET /api/coupon?isActive={isActive}&type={type}&search={search}

be_ctrl->sv++:3. Call GetAll(managerId, isActive, type, search, isAdmin=true)
sv->repo++:4. Call GetAllAsync(managerId=null, isActive, type, search)
repo->ctx++:5. Query Coupons
ctx->db++:6. Execute query
db-->>ctx--:7. Return result
ctx-->>repo--:8. Return list of Coupons
repo-->>sv--:9. Return list of Coupons

sv->res_dto++:10. Call CouponResponseDTO()
res_dto-->>sv--:11. Return CouponResponseDTO object

sv-->>be_ctrl--:12. Return list of CouponResponseDTO objects
be_ctrl-->>view--:13. Return statusCode 200
view-->>act--:14. Render Coupon List table
@enduml
