@startuml 
<style>
    sequenceDiagram{
        FontSize 16

        arrow {
            ' Set the maximum width of the text on arrows
            MaximumWidth 300

        }
        actor{
            BackgroundColor white
            LineThickness 1.0
        }
        participant{
            BackgroundColor white
            RoundCorner 0
        }
        database{
            BackgroundColor white
        }
        groupHeader{
            BackgroundColor white
        }
        referenceHeader{
            BackgroundColor white
        }
        reference{
            BackgroundColor white
        }
    }
</style>

hide footbox
mainframe Resolve Report

actor "Staff / Admin" as act
participant "ReportCenterPage" as view

    |||
    ref over act, view: Resolve Course Report
    |||
    ref over act, view: Resolve Course Review Report
    |||
    ref over act, view: Resolve Lesson Review Report

@enduml
